apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "customer-service.fullname" . }}
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      {{- include "customer-service.labels" . | nindent 6 }}
  endpoints:
    - port: http
      path: /metrics
      interval: 15s
