apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "restaurant-gateway.fullname" . }}
  labels:
    {{- include "restaurant-gateway.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "restaurant-gateway.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "restaurant-gateway.selectorLabels" . | nindent 8 }}
    spec:
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - name: http
          containerPort: {{ .Values.service.targetPort }}
          protocol: TCP
        env:
        {{- toYaml .Values.env | nindent 8 }}
        resources:
          {{- toYaml .Values.resources | nindent 10 }}
        readinessProbe:
          httpGet:
            path: /health
            port: http
          initialDelaySeconds: 30
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /health  
            port: http
          initialDelaySeconds: 60
          periodSeconds: 15
